name: Test and Build

on: [push, pull_request, workflow_dispatch]

jobs:
  test_and_build:
    name: Test and build ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        unityVersion: ["2019.4.18f1"]
        projectPath:
          - UnityExampleProject
        platform:
          - os: windows-latest
            cxx: cl
            cc: cl
          - os: ubuntu-latest
            cxx: g++-11
            cc: gcc-11
            install: sudo apt-get install freeglut3-dev g++-11 gcc-11
          - os: macos-latest
            cxx: clang++
            cc: clang
        buildType: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.platform.os }}-${{ matrix.unityVersion }}
          restore-keys: |
            Library-${{ matrix.platform.os }}-${{ matrix.unityVersion }}-
            Library-

      - uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          ${{ matrix.platform.install }}

      - uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.platform.os, 'windows')

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@ade188313bc7eaa6f14349569a64d8bc716342ff
        with:
          source-dir: ${{ github.workspace}}/NativePlugin
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.platform.cc }}
          cxx: ${{ matrix.platform.cxx }}
          configure-options: -G Ninja
          build-type: ${{ matrix.buildType }}

      # - uses: game-ci/unity-test-runner@v2
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     unityVersion: ${{ matrix.unityVersion }}
      #     projectPath: ${{ matrix.projectPath }}
      #     testMode: playmode
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # - uses: game-ci/unity-builder@v2
      #   #  only building on windows as the managed plugins are platform agnostic
      #   if: contains(matrix.platform.os, 'windows')
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     unityVersion: ${{ matrix.unityVersion }}
      #     projectPath: ${{ matrix.projectPath }}
      #     targetPlatform: StandaloneWindows64
      #     buildMethod: OpenglAsyncReadback.Editor.Build
      #     customParameters: -force-glcore -buildType ${{ matrix.buildType }}

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/Unity
          key: Unity-${{ matrix.platform.os }}-${{ matrix.unityVersion }}

      - uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unityVersion }}
          install-path: ${{ github.workspace }}/Unity

      - name: Activate unity
        run: |
          echo ${{ secrets.UNITY_LICENSE }} >> unity_license
          "${{ env.UNITY_PATH }}" -batchmode -manualLicenseFile unity_license -logfile -
          mkdir artifacts

      - name: Test
        run: >
          "${{ env.UNITY_PATH }}" -batchmode
            -logfile artifacts/test.log
            -projectPath ${{  matrix.projectPath }}
            -runTests
            -testPlatform playmode
            -testResults artifacts/results.xml
            -enableCodeCoverage
            -debugCodeOptimization
            -force-glcore
            -coverageOptions
            generateAdditionalMetrics;generateHtmlReport;generateBadgeReport

      - name: Build
        #  only building on windows as the managed plugins are platform agnostic
        if: contains(matrix.platform.os, 'windows')
        run: >
          "${{ env.UNITY_PATH }}" -batchmode
            -logfile artifacts/build.log
            -projectPath ${{  matrix.projectPath }}
            -executeMethod OpenglAsyncReadback.Editor.Build
            -buildType ${{ matrix.buildType }}

      - uses: actions/upload-artifact@v2
        with:
          name: UniversalAsyncGPUPlugin-${{ matrix.buildType }}
          path: |
            bin/*.dll
            bin/*.pdb
            bin/*.so
            bin/*.dylib
